DROP TABLE IF EXISTS validation_records;
DROP TABLE IF EXISTS exam_outcomes;
DROP TABLE IF EXISTS referral_codes;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS price_tiers;
DROP TABLE IF EXISTS supervised_feedback;
DROP TABLE IF EXISTS imaging_assets;
DROP TABLE IF EXISTS scenario_rubric_evidence;
DROP TABLE IF EXISTS scenario_rubrics;
ALTER TABLE competition_entries DROP COLUMN IF EXISTS integrity_status;
DROP TABLE IF EXISTS community_challenges;
DROP TABLE IF EXISTS community_group_members;
DROP TABLE IF EXISTS community_groups;
DROP TABLE IF EXISTS interoperability_receipts;
DROP TABLE IF EXISTS assessment_publications;
DROP TABLE IF EXISTS external_identities;
ALTER TABLE cohorts DROP COLUMN IF EXISTS program_id;
DROP TABLE IF EXISTS institution_programs;
DROP TABLE IF EXISTS intervention_outcomes;
DROP TABLE IF EXISTS coach_memory;
DROP TABLE IF EXISTS learner_accommodations;
DROP TABLE IF EXISTS assessment_forms;
DROP TABLE IF EXISTS exam_spec_versions;
ALTER TABLE exams DROP COLUMN IF EXISTS aliases;
ALTER TABLE exams DROP COLUMN IF EXISTS official_source_url;
DROP TABLE IF EXISTS user_devices;
ALTER TABLE auth_sessions DROP COLUMN IF EXISTS revoked_at;
ALTER TABLE auth_sessions DROP COLUMN IF EXISTS device_id;
ALTER TABLE users DROP COLUMN IF EXISTS deleted_at;
