[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain-contracts = { path = "../../crates/domain-contracts" }
calc-engine = { path = "../../crates/calc-engine" }
competition-scoring = { path = "../../crates/competition-scoring" }
scheduler = { path = "../../crates/scheduler" }
telemetry = { path = "../../crates/telemetry" }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
openidconnect = { workspace = true }
chacha20poly1305 = { workspace = true }
base64 = "0.22"
ed25519-dalek = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
rsa = "0.9"
jsonwebtoken = "9"
tower-http = { workspace = true }
calamine = "0.36.1"
csv = "1.4.0"
ts-rs = { version = "12.0.1", features = ["uuid-impl"], optional = true }

[features]
type-export = ["dep:ts-rs"]

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
